install:
  - cinst pester

build: false

test_script:
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
